# Groups the pull requests of the release notes that GitHub generates for a release, by label.
changelog:
  exclude:
    labels:
      - duplicate
      - invalid
      - wontfix
      - question
  categories:
    - title: New features
      labels:
        - enhancement
    - title: Bug fixes
      labels:
        - bug
        - bug-lo
        - bug-oo
    - title: Documentation
      labels:
        - documentation
    - title: Dependencies
      labels:
        - dependencies
    - title: Other changes
      labels:
        - "*"
